---
Name: flux-routes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    "flux/api//$Action": Flux\API\APIController
    "flux/component//$Action/$Component": Flux\Component\ComponentController
